multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/MZ_MCTS/mz_search_tree.py", line 231, in p_self_play
    game_results = tree.play_one_game(net, dev, dir_path=dir_path, calculate_avg_num_children=game == num_g - 1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/MZ_MCTS/mz_search_tree.py", line 57, in play_one_game
    pi, (v, latent) = self.search(network_wrapper, state, player, device, calculate_avg_num_children=(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/MZ_MCTS/mz_search_tree.py", line 88, in search
    state_ = network_wrapper.representation_forward(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/Network/networks.py", line 88, in representation_forward
    x = self.representation_network(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/Network/networks.py", line 235, in forward
    x = self.relu(self.conv1(x))
                  ^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 2, 6, 7] to have 3 channels, but got 2 channels instead
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/skyr/PycharmProjects/connect4mz/train_mz.py", line 169, in <module>
    train_mz()
  File "/home/skyr/PycharmProjects/connect4mz/train_mz.py", line 69, in train_mz
    mz.train()
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/muzero.py", line 98, in train
    self.trainer.train()
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/trainer.py", line 136, in train
    wins_p1, wins_p2, game_draws = self.mcts.parallel_self_play(self.make_n_networks(n_jobs),
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/mu_alpha_zero/MuZero/MZ_MCTS/mz_search_tree.py", line 184, in parallel_self_play
    results = p.starmap(p_self_play, [
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/multiprocess/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/miniconda3/envs/ai_stuff/lib/python3.11/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 2, 6, 7] to have 3 channels, but got 2 channels instead